GET http://localhost:3000/signup

###

GET http://localhost:3000/users/656241aaa35d3d5673000005

###

POST http://localhost:3000/signup
Content-Type: application/json

{
    "email": "asdas@asdasd.asd",
    "password": "123456"

}

###

DELETE http://localhost:3000/users/65624193db222ab63d74f363

###

PATCH http://localhost:3000/users/656241aaa35d3d5673000005
Content-Type: application/json

{
    "name": "1 Million Lucky"

}